---
- hosts: all
  become: yes
  remote_user: centos
  tasks:
    - name: Change user password
      user:
        name: centos
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
