---
- hosts: group06
  tasks:
    - name: Installing wget Package
      pkgng:
        name: wget
        state: latest

    - name: Copy file with owner and permission
      copy:
        src: /etc/rc.conf
        dest: /home/ansible/new-rc.conf
        owner: ansible
        group: ansible
        mode: '0644'
...
