---
- hosts: group06, redhat, debian
  become: yes
  tasks:
    - name: install services on Debian machines
      apt:
        name:
          - apache2
          - nginx
          - bind9
          - mariadb-server
        state: latest
      when:
        ansible_os_family == 'Debian'

    - name: install services on RedHat machines
      yum:
        name:
          - httpd
          - nginx
          - bind
          - mariadb
        state: latest
      when:
        ansible_os_family == 'RedHat'

    - name: install services on FreeBSD
      pkgng:
        name:
          - apache24
          - nginx
          - bind916
          - mariadb105-server
        state: latest
      when:
        ansible_os_family == 'FreeBSD'

...
